// Generated by scripts/build-inject.js. Edit src/inject-main.js or src/shared/*.js instead.
(() => {
  // src/shared/quality.js
  var QUALITY_RE = /(?:^|[^0-9])(\d{3,4})\s*p(?:[^0-9]|$)/i;
  var RESOLUTION_RE = /(?:RESOLUTION=|^)(\d{3,5})x(\d{3,5})(?:[,\s]|$)/i;
  function normalizeQualityLabel(value) {
    if (typeof value !== "string") return null;
    const resolutionMatch = value.match(RESOLUTION_RE);
    if (resolutionMatch) return `${Number(resolutionMatch[2])}p`;
    const qualityMatch = value.match(QUALITY_RE);
    if (!qualityMatch) return null;
    return `${Number(qualityMatch[1])}p`;
  }
  function qualityRank(label) {
    const normalized = normalizeQualityLabel(label);
    if (!normalized) return -1;
    return Number(normalized.slice(0, -1));
  }
  function chooseHighestQuality(labels) {
    if (!Array.isArray(labels) || labels.length === 0) return null;
    const normalizedLabels = [...new Set(labels.map(normalizeQualityLabel).filter(Boolean))];
    if (normalizedLabels.length === 0) return null;
    return normalizedLabels.sort((a, b) => qualityRank(b) - qualityRank(a))[0];
  }
  function choosePreferredVisibleQuality(visibleLabels, storedPreference = null) {
    const normalizedVisibleLabels = [
      ...new Set((visibleLabels ?? []).map(normalizeQualityLabel).filter(Boolean))
    ];
    if (normalizedVisibleLabels.length === 0) return null;
    const normalizedPreference = normalizeQualityLabel(storedPreference);
    if (normalizedPreference && normalizedVisibleLabels.includes(normalizedPreference))
      return normalizedPreference;
    return chooseHighestQuality(normalizedVisibleLabels);
  }
  function parseQualityFromUrl(url) {
    if (typeof url !== "string") return null;
    let pathname = url;
    try {
      pathname = new URL(url).pathname;
    } catch {
      pathname = url.split("?")[0].split("#")[0];
    }
    return normalizeQualityLabel(pathname);
  }
  function redactMediaUrl(url) {
    if (typeof url !== "string" || url === "") return "";
    try {
      const parsed = new URL(url);
      const hadSensitiveTail = parsed.search || parsed.hash;
      parsed.search = "";
      parsed.hash = "";
      return `${parsed.toString()}${hadSensitiveTail ? "?[redacted]" : ""}`;
    } catch {
      return url.replace(/[?#].*$/, "?[redacted]");
    }
  }

  // src/shared/player-dom.js
  var QUALITY_LIST_SELECTOR = "ul.pzp-setting-quality-pane__list-container";
  var QUALITY_ITEM_SELECTORS = [
    `${QUALITY_LIST_SELECTOR} > li`,
    "li.pzp-ui-setting-quality-item",
    "[class*='setting-quality'] li"
  ];
  function safeText(element) {
    return element?.innerText?.trim() ?? element?.textContent?.trim() ?? "";
  }
  function getQualityItems(documentRef = globalThis.document) {
    if (!documentRef?.querySelectorAll) return [];
    const seen = /* @__PURE__ */ new Set();
    const items = [];
    for (const selector of QUALITY_ITEM_SELECTORS) {
      for (const element of documentRef.querySelectorAll(selector)) {
        if (seen.has(element)) continue;
        seen.add(element);
        if (normalizeQualityLabel(safeText(element))) items.push(element);
      }
    }
    return items;
  }
  function getVisibleQualityLabels(documentRef = globalThis.document) {
    return getQualityItems(documentRef).map((element) => normalizeQualityLabel(safeText(element))).filter(Boolean);
  }
  function findQualityItem(documentRef, label) {
    const normalized = normalizeQualityLabel(label);
    if (!normalized) return null;
    return getQualityItems(documentRef).find((element) => normalizeQualityLabel(safeText(element)) === normalized) ?? null;
  }
  function findCheckedQualityItem(documentRef = globalThis.document) {
    return documentRef?.querySelector?.("li.pzp-ui-setting-pane-item--checked") ?? documentRef?.querySelector?.("li[aria-selected='true']") ?? null;
  }
  function createBadge(documentRef = globalThis.document, badgeText = "CHZZK") {
    const badgeWrap = documentRef.createElement("div");
    badgeWrap.className = "pzp-ui-track-badge";
    const badge = documentRef.createElement("em");
    badge.className = "pzp-ui-track-badge__badge";
    badge.style.verticalAlign = "super";
    badge.textContent = badgeText;
    badgeWrap.append(badge);
    return badgeWrap;
  }
  function setQualityItemDisplay(element, label, { document: documentRef = globalThis.document, badgeText = "CHZZK" } = {}) {
    if (!element || !label || !documentRef) return false;
    const target = element.querySelector("li > div:nth-child(2) > span > div") ?? element.querySelector("span") ?? element;
    const prefix = documentRef.createElement("span");
    prefix.className = "pzp-pc-ui-setting-quality-item__prefix";
    prefix.append(documentRef.createTextNode(`${label}\xA0`), createBadge(documentRef, badgeText));
    target.replaceChildren(prefix);
    return true;
  }
  function updateCurrentQualityText(documentRef, targetQuality, { badgeText = "CHZZK" } = {}) {
    const currentQualityTextElement = documentRef?.querySelector?.(
      "div.pzp-setting-intro-quality > div > div:last-child > span.pzp-ui-setting-home-item__value"
    );
    const checkedQuality = normalizeQualityLabel(safeText(findCheckedQualityItem(documentRef)));
    if (!currentQualityTextElement || checkedQuality !== targetQuality) return false;
    currentQualityTextElement.replaceChildren(
      documentRef.createTextNode(`${targetQuality} `),
      createBadge(documentRef, badgeText)
    );
    return true;
  }

  // src/inject-main.js
  var LOG_PREFIX = "[CHZZK]";
  var STORAGE_KEY = "chzzk.selectedQualityText";
  var BADGE_TEXT = "CHZZK";
  var LIVE_URL_RE = /^https:\/\/chzzk\.naver\.com\/live\/[0-9a-z]+/i;
  var MEDIA_PLAYLIST_RE = /\.m3u8(?:[?#]|$)/i;
  var qualityListElement = null;
  var observerTick = 0;
  var performanceScanCursor = 0;
  var lastQualityDiagnostic = "";
  var observedQualities = /* @__PURE__ */ new Set();
  function log(...args) {
    console.log(LOG_PREFIX, ...args);
  }
  function warn(...args) {
    console.warn(LOG_PREFIX, ...args);
  }
  function isLivePage() {
    return LIVE_URL_RE.test(location.href);
  }
  function recordMediaUrl(url) {
    if (typeof url !== "string" || !MEDIA_PLAYLIST_RE.test(url)) return;
    const quality = parseQualityFromUrl(url);
    if (!quality) return;
    observedQualities.add(quality);
    const highestQuality = chooseHighestQuality([...observedQualities]);
    const diagnosticKey = `${highestQuality}:${[...observedQualities].sort().join(",")}`;
    if (diagnosticKey === lastQualityDiagnostic) return;
    lastQualityDiagnostic = diagnosticKey;
    log("observed HLS qualities", {
      highestQuality,
      qualities: [...observedQualities].sort((a, b) => qualityRank(a) - qualityRank(b)),
      sampleUrl: redactMediaUrl(url)
    });
  }
  function scanPerformanceEntries() {
    if (!globalThis.performance?.getEntriesByType) return;
    const entries = performance.getEntriesByType("resource");
    for (let index = performanceScanCursor; index < entries.length; index += 1) {
      recordMediaUrl(entries[index]?.name);
    }
    performanceScanCursor = entries.length;
  }
  function startMediaDiagnostics() {
    scanPerformanceEntries();
    if (!globalThis.PerformanceObserver) return;
    try {
      const performanceObserver = new PerformanceObserver((list) => {
        for (const entry of list.getEntries()) recordMediaUrl(entry.name);
      });
      performanceObserver.observe({ type: "resource", buffered: true });
    } catch (error) {
      warn("media diagnostics unavailable", error);
    }
  }
  function updateQualityText() {
    const targetQuality = choosePreferredVisibleQuality(
      getVisibleQualityLabels(document),
      localStorage.getItem(STORAGE_KEY)
    );
    if (!targetQuality) return false;
    const targetQualityItem = findQualityItem(document, targetQuality);
    if (!targetQualityItem) return false;
    const changed = setQualityItemDisplay(targetQualityItem, targetQuality, {
      badgeText: BADGE_TEXT,
      document
    });
    updateCurrentQualityText(document, targetQuality, { badgeText: BADGE_TEXT });
    return changed;
  }
  function openQualityMenu() {
    const settingsButton = document.querySelector(
      "button.pzp-setting-button[command='SettingCommands.Toggle']"
    );
    const qualityIntro = document.querySelector("div.pzp-setting-intro-quality");
    settingsButton?.click();
    qualityIntro?.click();
  }
  function selectQuality(label) {
    const item = findQualityItem(document, label);
    if (!item) return false;
    item.dispatchEvent(new KeyboardEvent("keydown", { bubbles: true, key: "Enter" }));
    item.click?.();
    return true;
  }
  function restoreQuality() {
    const targetQuality = choosePreferredVisibleQuality(
      getVisibleQualityLabels(document),
      localStorage.getItem(STORAGE_KEY)
    );
    if (!targetQuality) return;
    const currentQuality = normalizeQualityLabel(safeText(findCheckedQualityItem(document)));
    if (currentQuality === targetQuality) return;
    const videoElement = document.querySelector("video.webplayer-internal-video");
    if (!videoElement || videoElement.readyState < 2) return;
    openQualityMenu();
    if (selectQuality(targetQuality)) {
      updateQualityText();
      log("requested quality", targetQuality);
    }
  }
  function saveQuality() {
    window.setTimeout(() => {
      const selectedQuality = normalizeQualityLabel(safeText(findCheckedQualityItem(document)));
      if (!selectedQuality) return;
      localStorage.setItem(STORAGE_KEY, selectedQuality);
    }, 0);
  }
  function bindQualityListEvents() {
    const list = document.querySelector(QUALITY_LIST_SELECTOR);
    if (!list || list === qualityListElement) return;
    qualityListElement?.removeEventListener("click", saveQuality);
    qualityListElement?.removeEventListener("keydown", saveQuality);
    qualityListElement = list;
    qualityListElement.addEventListener("click", saveQuality);
    qualityListElement.addEventListener("keydown", saveQuality);
  }
  function tick() {
    if (document.readyState !== "complete" || !isLivePage()) return;
    try {
      scanPerformanceEntries();
      updateQualityText();
      bindQualityListEvents();
      restoreQuality();
    } catch (error) {
      warn("quality controller failed", error);
    }
  }
  function scheduleTick() {
    window.clearTimeout(observerTick);
    observerTick = window.setTimeout(tick, 250);
  }
  if (!globalThis.__CHZZK_EXTENSION_INJECTED__) {
    globalThis.__CHZZK_EXTENSION_INJECTED__ = true;
    log("page script injected");
    startMediaDiagnostics();
    const observer = new MutationObserver(scheduleTick);
    observer.observe(document.body, {
      attributeFilter: ["class", "aria-selected"],
      attributes: true,
      childList: true,
      subtree: true
    });
    scheduleTick();
  }
})();
