// Generated by scripts/build-inject.js. Edit src/inject-main.js or src/shared/*.js instead.
(() => {
  // src/shared/quality.js
  var SOURCE_QUALITY = "480p";
  var TARGET_QUALITY = "1080p";
  var QUALITY_RE = /(?:^|[^0-9])(\d{3,4})\s*p(?:[^0-9]|$)/i;
  var RESOLUTION_RE = /(?:RESOLUTION=|^)(\d{3,5})x(\d{3,5})(?:[,\s]|$)/i;
  function normalizeQualityLabel(value) {
    if (typeof value !== "string") return null;
    const resolutionMatch = value.match(RESOLUTION_RE);
    if (resolutionMatch) return `${Number(resolutionMatch[2])}p`;
    const qualityMatch = value.match(QUALITY_RE);
    if (!qualityMatch) return null;
    return `${Number(qualityMatch[1])}p`;
  }
  function parseQualityFromUrl(url) {
    if (typeof url !== "string") return null;
    let pathname = url;
    try {
      pathname = new URL(url).pathname;
    } catch {
      pathname = url.split("?")[0].split("#")[0];
    }
    return normalizeQualityLabel(pathname);
  }
  function redactMediaUrl(url) {
    if (typeof url !== "string" || url === "") return "";
    try {
      const parsed = new URL(url);
      const hadSensitiveTail = parsed.search || parsed.hash;
      parsed.search = "";
      parsed.hash = "";
      return `${parsed.toString()}${hadSensitiveTail ? "?[redacted]" : ""}`;
    } catch {
      return url.replace(/[?#].*$/, "?[redacted]");
    }
  }

  // src/shared/player-dom.js
  var GRID_BYPASS_DISPLAY_QUALITY = TARGET_QUALITY;
  var GRID_BYPASS_BADGE_TEXT = "with CHZZK GRID\u2122";
  var GRID_BYPASS_STORAGE_VALUE = SOURCE_QUALITY;
  var QUALITY_LIST_SELECTOR = "ul.pzp-setting-quality-pane__list-container";
  var QUALITY_ITEM_SELECTOR = `${QUALITY_LIST_SELECTOR} > li`;
  var GRID_BYPASS_SOURCE_ATTRIBUTE = "data-chzzk-grid-bypass-source";
  function safeText(element) {
    return element?.innerText?.trim() ?? element?.textContent?.trim() ?? "";
  }
  function isGridBypassItem(element) {
    if (!element) return false;
    return element.getAttribute?.(GRID_BYPASS_SOURCE_ATTRIBUTE) === SOURCE_QUALITY || safeText(element).includes(GRID_BYPASS_BADGE_TEXT);
  }
  function findQualityItems(documentRef = globalThis.document) {
    return [...documentRef?.querySelectorAll?.(QUALITY_ITEM_SELECTOR) ?? []];
  }
  function findSourceQualityItem(documentRef = globalThis.document) {
    return findQualityItems(documentRef).find(
      (element) => isGridBypassItem(element) || normalizeQualityLabel(safeText(element)) === SOURCE_QUALITY
    ) ?? null;
  }
  function findCheckedQualityItem(documentRef = globalThis.document) {
    return documentRef?.querySelector?.(`${QUALITY_ITEM_SELECTOR}.pzp-ui-setting-pane-item--checked`) ?? documentRef?.querySelector?.(`${QUALITY_ITEM_SELECTOR}[aria-selected='true']`) ?? documentRef?.querySelector?.("li.pzp-ui-setting-pane-item--checked") ?? documentRef?.querySelector?.("li[aria-selected='true']") ?? null;
  }
  function createGridBypassBadge(documentRef = globalThis.document) {
    const badgeWrap = documentRef.createElement("div");
    badgeWrap.className = "pzp-ui-track-badge";
    const badge = documentRef.createElement("em");
    badge.className = "pzp-ui-track-badge__badge";
    badge.style.verticalAlign = "super";
    badge.textContent = GRID_BYPASS_BADGE_TEXT;
    badgeWrap.append(badge);
    return badgeWrap;
  }
  function renderGridBypassQualityLabel(element, { document: documentRef = globalThis.document } = {}) {
    if (!element || !documentRef) return false;
    const target = element.querySelector("li > div:nth-child(2) > span > div") ?? element.querySelector("span") ?? element;
    const prefix = documentRef.createElement("span");
    prefix.className = "pzp-pc-ui-setting-quality-item__prefix";
    prefix.append(
      documentRef.createTextNode(`${GRID_BYPASS_DISPLAY_QUALITY}\xA0`),
      createGridBypassBadge(documentRef)
    );
    target.replaceChildren(prefix);
    element.setAttribute(GRID_BYPASS_SOURCE_ATTRIBUTE, SOURCE_QUALITY);
    return true;
  }
  function updateCurrentGridBypassQualityText(documentRef = globalThis.document) {
    const currentQualityTextElement = documentRef?.querySelector?.(
      "div.pzp-setting-intro-quality > div > div:last-child > span.pzp-ui-setting-home-item__value"
    );
    const selectedQuality = findCheckedQualityItem(documentRef);
    if (!currentQualityTextElement || !isGridBypassItem(selectedQuality)) return false;
    currentQualityTextElement.replaceChildren(
      documentRef.createTextNode(`${GRID_BYPASS_DISPLAY_QUALITY} `),
      createGridBypassBadge(documentRef)
    );
    return true;
  }
  function canonicalStoredQualityForItem(element) {
    if (!element) return null;
    if (isGridBypassItem(element)) return GRID_BYPASS_STORAGE_VALUE;
    return normalizeQualityLabel(safeText(element));
  }
  function findQualityItemByStoredValue(documentRef, storedQuality) {
    const normalizedStoredQuality = normalizeQualityLabel(storedQuality);
    if (!normalizedStoredQuality) return null;
    if (normalizedStoredQuality === GRID_BYPASS_STORAGE_VALUE) {
      return findSourceQualityItem(documentRef);
    }
    return findQualityItems(documentRef).find(
      (element) => normalizeQualityLabel(safeText(element)) === normalizedStoredQuality
    ) ?? null;
  }

  // src/inject-main.js
  var LOG_PREFIX = "[CHZZK]";
  var STORAGE_KEY = "chzzk.gridBypass.selectedQuality";
  var LIVE_URL_RE = /^https:\/\/chzzk\.naver\.com\/live\/[0-9a-z]+/i;
  var MEDIA_PLAYLIST_RE = /\.m3u8(?:[?#]|$)/i;
  var DEFAULT_STORED_QUALITY = "360p";
  var RESTORE_THROTTLE_MS = 1e3;
  var qualityListElement = null;
  var observerTick = 0;
  var performanceScanCursor = 0;
  var previousIntroQualityText = "";
  var previousRestoreAttempt = 0;
  var lastObservedRedirectPair = "";
  function log(...args) {
    console.log(LOG_PREFIX, ...args);
  }
  function warn(...args) {
    console.warn(LOG_PREFIX, ...args);
  }
  function isLivePage() {
    return LIVE_URL_RE.test(location.href);
  }
  function recordMediaUrl(url) {
    if (typeof url !== "string" || !MEDIA_PLAYLIST_RE.test(url)) return;
    const quality = parseQualityFromUrl(url);
    if (!quality) return;
    const pairKey = `${quality}:${redactMediaUrl(url)}`;
    if (quality !== SOURCE_QUALITY && quality !== TARGET_QUALITY) return;
    if (pairKey === lastObservedRedirectPair) return;
    lastObservedRedirectPair = pairKey;
    log("observed HLS playlist", {
      quality,
      sampleUrl: redactMediaUrl(url)
    });
  }
  function scanPerformanceEntries() {
    if (!globalThis.performance?.getEntriesByType) return;
    const entries = performance.getEntriesByType("resource");
    for (let index = performanceScanCursor; index < entries.length; index += 1) {
      recordMediaUrl(entries[index]?.name);
    }
    performanceScanCursor = entries.length;
  }
  function startMediaDiagnostics() {
    scanPerformanceEntries();
    if (!globalThis.PerformanceObserver) return;
    try {
      const performanceObserver = new PerformanceObserver((list) => {
        for (const entry of list.getEntries()) recordMediaUrl(entry.name);
      });
      performanceObserver.observe({ type: "resource", buffered: true });
    } catch (error) {
      warn("media diagnostics unavailable", error);
    }
  }
  function renderGridBypassOption() {
    const sourceQualityItem = findSourceQualityItem(document);
    if (!sourceQualityItem) return false;
    return renderGridBypassQualityLabel(sourceQualityItem, { document });
  }
  function syncIntroQualityText() {
    if (updateCurrentGridBypassQualityText(document)) return;
    const currentQualityTextElement = document.querySelector(
      "div.pzp-setting-intro-quality > div > div:last-child > span.pzp-ui-setting-home-item__value"
    );
    const selectedQualityText = safeText(findCheckedQualityItem(document));
    if (!currentQualityTextElement || !selectedQualityText) return;
    const introText = safeText(currentQualityTextElement);
    if (previousIntroQualityText !== introText) {
      currentQualityTextElement.textContent = selectedQualityText;
      previousIntroQualityText = selectedQualityText;
    }
  }
  function openQualityMenu() {
    const settingsButton = document.querySelector(
      "button.pzp-setting-button[command='SettingCommands.Toggle']"
    );
    const qualityIntro = document.querySelector("div.pzp-setting-intro-quality");
    settingsButton?.click();
    qualityIntro?.click();
  }
  function selectStoredQuality(storedQuality) {
    const item = findQualityItemByStoredValue(document, storedQuality);
    if (!item) return false;
    item.dispatchEvent(new KeyboardEvent("keydown", { bubbles: true, key: "Enter" }));
    item.click?.();
    return true;
  }
  function restoreQuality() {
    const now = Date.now();
    if (now - previousRestoreAttempt < RESTORE_THROTTLE_MS) return;
    previousRestoreAttempt = now;
    const qualityList = document.querySelector(QUALITY_LIST_SELECTOR);
    if (!qualityList) return;
    const storedQuality = localStorage.getItem(STORAGE_KEY) ?? DEFAULT_STORED_QUALITY;
    const currentQuality = canonicalStoredQualityForItem(findCheckedQualityItem(document));
    if (currentQuality === storedQuality) return;
    const videoElement = document.querySelector("video.webplayer-internal-video");
    if (!videoElement || videoElement.readyState < 3) return;
    openQualityMenu();
    renderGridBypassOption();
    if (selectStoredQuality(storedQuality)) {
      renderGridBypassOption();
      syncIntroQualityText();
      log("requested quality", storedQuality === GRID_BYPASS_STORAGE_VALUE ? TARGET_QUALITY : storedQuality);
    }
  }
  function saveQuality() {
    window.setTimeout(() => {
      const storedQuality = canonicalStoredQualityForItem(findCheckedQualityItem(document));
      if (!storedQuality) return;
      localStorage.setItem(STORAGE_KEY, storedQuality);
    }, 0);
  }
  function bindQualityListEvents() {
    const list = document.querySelector(QUALITY_LIST_SELECTOR);
    if (!list || list === qualityListElement) return;
    qualityListElement?.removeEventListener("click", saveQuality);
    qualityListElement?.removeEventListener("keydown", saveQuality);
    qualityListElement = list;
    qualityListElement.addEventListener("click", saveQuality);
    qualityListElement.addEventListener("keydown", saveQuality);
  }
  function tick() {
    if (document.readyState !== "complete" || !isLivePage()) return;
    try {
      scanPerformanceEntries();
      renderGridBypassOption();
      syncIntroQualityText();
      bindQualityListEvents();
      restoreQuality();
    } catch (error) {
      warn("grid bypass controller failed", error);
    }
  }
  function scheduleTick() {
    window.clearTimeout(observerTick);
    observerTick = window.setTimeout(tick, 250);
  }
  if (!globalThis.__CHZZK_GRID_BYPASS_INJECTED__) {
    globalThis.__CHZZK_GRID_BYPASS_INJECTED__ = true;
    log("grid bypass page script injected");
    startMediaDiagnostics();
    const observer = new MutationObserver(scheduleTick);
    observer.observe(document.body, {
      attributeFilter: ["class", "aria-selected"],
      attributes: true,
      childList: true,
      subtree: true
    });
    scheduleTick();
  }
})();
