import { build } from "esbuild";

await build({
  banner: {
    js: "// Generated by scripts/build-inject.js. Edit src/inject-main.js or src/shared/*.js instead.",
  },
  bundle: true,
  entryPoints: ["src/inject-main.js"],
  format: "iife",
  legalComments: "none",
  logLevel: "info",
  outfile: "inject.js",
  platform: "browser",
  target: ["firefox140"],
});
